filebeat.inputs:
  - type: log
    paths:
      - /var/log/zeek/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: ""

setup.kibana:
  host: "kibana:5601"

