version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  zeek:
    build: ./zeek
    volumes:
      - ./zeek/logs:/opt/zeek/logs/current

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./zeek/logs:/var/log/zeek
    depends_on:
      - elasticsearch

  ml-detector:
    build: ./ml
    volumes:
      - ./zeek/logs:/data
    depends_on:
      - zeek

